In [1]:
import pandas as pd
import numpy as np
import itertools

from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.metrics import *
from imblearn.metrics import *

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.ensemble import StackingClassifier
from mlxtend.classifier import StackingCVClassifier

from sklearn.neural_network import MLPClassifier


from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import matplotlib.pyplot as plt

In [2]:
data= pd.read_csv('phishing_uci.csv', header=None)
data

0   1   2   3   4   5   6   7   8   9   ...  21  22  23  24  25  26  \
0      -1   1   1   1  -1  -1  -1  -1  -1   1  ...   1   1  -1  -1  -1  -1   
1       1   1   1   1   1  -1   0   1  -1   1  ...   1   1  -1  -1   0  -1   
2       1   0   1   1   1  -1  -1  -1  -1   1  ...   1   1   1  -1   1  -1   
3       1   0   1   1   1  -1  -1  -1   1   1  ...   1   1  -1  -1   1  -1   
4       1   0  -1   1   1  -1   1   1  -1   1  ...  -1   1  -1  -1   0  -1   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
11050   1  -1   1  -1   1   1   1   1  -1  -1  ...  -1  -1   1   1  -1  -1   
11051  -1   1   1  -1  -1  -1   1  -1  -1  -1  ...  -1   1   1   1   1   1   
11052   1  -1   1   1   1  -1   1  -1  -1   1  ...   1   1   1   1   1  -1   
11053  -1  -1   1   1   1  -1  -1  -1   1  -1  ...  -1   1   1   1   1  -1   
11054  -1  -1   1   1   1  -1  -1  -1   1   1  ...   1   1  -1   1  -1  -1   

       27  28  29  30  
0       1   1  -1  -1  
1       1   1   1  -1  
2       1   0  -1  -1  
3       1  -1   1  -1  
4       1   1   1   1  
...    ..  ..  ..  ..  
11050   1   1   1   1  
11051   1  -1   1  -1  
11052   1   0   1  -1  
11053   1   1   1  -1  
11054  -1   1  -1  -1  

[11055 rows x 31 columns]

In [3]:
x= data.drop([30],axis=1)
x

0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  \
0      -1   1   1   1  -1  -1  -1  -1  -1   1  ...   1   1   1  -1  -1  -1   
1       1   1   1   1   1  -1   0   1  -1   1  ...   1   1   1  -1  -1   0   
2       1   0   1   1   1  -1  -1  -1  -1   1  ...   1   1   1   1  -1   1   
3       1   0   1   1   1  -1  -1  -1   1   1  ...   1   1   1  -1  -1   1   
4       1   0  -1   1   1  -1   1   1  -1   1  ...   1  -1   1  -1  -1   0   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
11050   1  -1   1  -1   1   1   1   1  -1  -1  ...  -1  -1  -1   1   1  -1   
11051  -1   1   1  -1  -1  -1   1  -1  -1  -1  ...   1  -1   1   1   1   1   
11052   1  -1   1   1   1  -1   1  -1  -1   1  ...   1   1   1   1   1   1   
11053  -1  -1   1   1   1  -1  -1  -1   1  -1  ...   1  -1   1   1   1   1   
11054  -1  -1   1   1   1  -1  -1  -1   1   1  ...   1   1   1  -1   1  -1   

       26  27  28  29  
0      -1   1   1  -1  
1      -1   1   1   1  
2      -1   1   0  -1  
3      -1   1  -1   1  
4      -1   1   1   1  
...    ..  ..  ..  ..  
11050  -1   1   1   1  
11051   1   1  -1   1  
11052  -1   1   0   1  
11053  -1   1   1   1  
11054  -1  -1   1  -1  

[11055 rows x 30 columns]

In [4]:
y=data[30]
y

0       -1
1       -1
2       -1
3       -1
4        1
        ..
11050    1
11051   -1
11052   -1
11053   -1
11054   -1
Name: 30, Length: 11055, dtype: int64

In [5]:
x_train=x
y_train=y

In [6]:
y.replace(-1,0,inplace=True)
y

0        0
1        0
2        0
3        0
4        1
        ..
11050    1
11051    0
11052    0
11053    0
11054    0
Name: 30, Length: 11055, dtype: int64

# defining models

In [7]:
knn= KNeighborsClassifier(n_neighbors=10,n_jobs=-1)
svm= SVC(random_state=10,kernel='linear', probability = True)
lr = LogisticRegression()
nb= GaussianNB()

rf= RandomForestClassifier(n_jobs=-1,random_state=10)
ada= AdaBoostClassifier(random_state=100)
extra = ExtraTreesClassifier(n_jobs=-1,random_state=10)

lgbm = LGBMClassifier(n_jobs=-1,random_state=10)
grad = GradientBoostingClassifier()
xg = XGBClassifier(use_label_encoder =False, eval_metric='logloss')

nn= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (32,32,32), random_state=10)

In [8]:
classifiers= {
    "RandomForest": rf,
    "ExtraTree": extra,
    "gradBoost": grad,
    "adaboost": ada,
    "LGBM": lgbm,
    "xgb": xg,
    "nn":nn}

In [9]:
classifier_2 = nn

In [10]:
scores={'accuracy': make_scorer(accuracy_score),
        'recall' : make_scorer(recall_score),
        'precision':make_scorer(precision_score),
        'gmean': make_scorer(geometric_mean_score),
        'f1':make_scorer(f1_score),
        'roc': make_scorer(roc_auc_score)
        }

# base models

In [29]:
rf_result = cross_validate(rf, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(rf_result)
df.mean(axis=0)

fit_time          0.228442
score_time        0.024980
test_accuracy     0.972769
test_recall       0.982295
test_precision    0.969354
test_gmean        0.971454
test_f1           0.975745
test_roc          0.971545
dtype: float64

In [30]:
ada_result= cross_validate(ada, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(ada_result)
df.mean(axis=0)

fit_time          0.230353
score_time        0.012603
test_accuracy     0.932520
test_recall       0.953387
test_precision    0.927578
test_gmean        0.929507
test_f1           0.940270
test_roc          0.929838
dtype: float64

In [31]:
extra_result= cross_validate(extra, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(extra_result)
df.mean(axis=0)

fit_time          0.232752
score_time        0.024972
test_accuracy     0.973673
test_recall       0.979045
test_precision    0.973941
test_gmean        0.972933
test_f1           0.976447
test_roc          0.972983
dtype: float64

In [32]:
grad_result= cross_validate(grad, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(grad_result)
df.mean(axis=0)

fit_time          0.643747
score_time        0.005901
test_accuracy     0.946993
test_recall       0.960860
test_precision    0.945014
test_gmean        0.945048
test_f1           0.952832
test_roc          0.945210
dtype: float64

In [33]:
lgbm_result= cross_validate(lgbm, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(lgbm_result)
df.mean(axis=0)

fit_time          0.065515
score_time        0.006801
test_accuracy     0.968790
test_recall       0.976774
test_precision    0.967650
test_gmean        0.967686
test_f1           0.972148
test_roc          0.967764
dtype: float64

In [36]:
xg_result= cross_validate(xg, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(xg_result)
df.mean(axis=0)

fit_time          0.196944
score_time        0.008302
test_accuracy     0.972860
test_recall       0.981970
test_precision    0.969804
test_gmean        0.971609
test_f1           0.975821
test_roc          0.971691
dtype: float64

In [37]:
nn_result= cross_validate(nn, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(nn_result)
df.mean(axis=0)

fit_time          4.273268
score_time        0.004901
test_accuracy     0.966708
test_recall       0.975634
test_precision    0.965185
test_gmean        0.965429
test_f1           0.970265
test_roc          0.965564
dtype: float64

In [38]:
svm_result= cross_validate(svm, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(svm_result)
df.mean(axis=0)

fit_time          0.799682
score_time        0.151434
test_accuracy     0.947444
test_recall       0.967680
test_precision    0.939864
test_gmean        0.944538
test_f1           0.953538
test_roc          0.944845
dtype: float64

In [10]:
knn_result= cross_validate(knn, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(knn_result)
df.mean(axis=0)

fit_time          0.004545
score_time        0.283732
test_accuracy     0.935953
test_recall       0.936167
test_precision    0.948253
test_gmean        0.935904
test_f1           0.942141
test_roc          0.935928
dtype: float64

In [11]:
lr_result= cross_validate(lr, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(lr_result)
df.mean(axis=0)

fit_time          0.033066
score_time        0.004074
test_accuracy     0.925373
test_recall       0.943966
test_precision    0.923816
test_gmean        0.922715
test_f1           0.933752
test_roc          0.922983
dtype: float64

In [12]:
nb= GaussianNB()
nb_result= cross_validate(nb, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(nb_result)
df.mean(axis=0)

fit_time          0.003873
score_time        0.005563
test_accuracy     0.603890
test_recall       0.289921
test_precision    0.996033
test_gmean        0.537729
test_f1           0.448739
test_roc          0.644246
dtype: float64

# stacking - proba

In [12]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, ada, extra, lgbm, grad, xg, nn]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)


In [14]:
df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          21.672631
score_time         0.083033
test_accuracy      0.974759
test_recall        0.984243
test_precision     0.971064
test_gmean         0.973425
test_f1            0.977543
test_roc           0.973541
dtype: float64

In [14]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, ada, extra, lgbm, grad, xg, nn, svm, knn]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)


In [15]:
df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          86.953716
score_time         0.732831
test_accuracy      0.973312
test_recall        0.981807
test_precision     0.970724
test_gmean         0.972145
test_f1            0.976199
test_roc           0.972221
dtype: float64

In [12]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, extra, xg, nn]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)


In [13]:
df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          51.641527
score_time         0.190220
test_accuracy      0.974125
test_recall        0.982781
test_precision     0.971250
test_gmean         0.972927
test_f1            0.976935
test_roc           0.973015
dtype: float64

In [14]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, extra, xg, nn, lgbm]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)

df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          50.533804
score_time         0.079677
test_accuracy      0.973854
test_recall        0.984243
test_precision     0.969397
test_gmean         0.972421
test_f1            0.976730
test_roc           0.972521
dtype: float64

In [16]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, extra, xg, nn, lgbm, svm, grad]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)

df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          86.598816
score_time         0.155767
test_accuracy      0.973583
test_recall        0.984569
test_precision     0.968646
test_gmean         0.972065
test_f1            0.976512
test_roc           0.972174
dtype: float64

In [17]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, extra, xg, nn, lgbm, svm]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)

df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          75.842267
score_time         0.162100
test_accuracy      0.973311
test_recall        0.984568
test_precision     0.968251
test_gmean         0.971727
test_f1            0.976273
test_roc           0.971867
dtype: float64

In [18]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, extra, xg, nn, lgbm, grad]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)

df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          63.995371
score_time         0.073417
test_accuracy      0.973311
test_recall        0.983755
test_precision     0.968986
test_gmean         0.971842
test_f1            0.976240
test_roc           0.971971
dtype: float64

In [19]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, extra, xg, nn, lgbm, knn]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)

df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          51.146189
score_time         0.347778
test_accuracy      0.973492
test_recall        0.983269
test_precision     0.969789
test_gmean         0.972116
test_f1            0.976416
test_roc           0.972237
dtype: float64

# feature selection

In [12]:
from sklearn.feature_selection import RFECV

In [16]:
selector = RFECV(rf, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
rf_col,= np.where(selector.ranking_==1)
rf_col

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64)

In [17]:
selector = RFECV(ada, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
ada_col,= np.where(selector.ranking_==1)
ada_col

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 13, 14, 15, 18, 24, 25, 26, 27,
       28], dtype=int64)

In [18]:
selector = RFECV(extra, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
extra_col= np.where(selector.ranking_==1)
extra_col

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64),)

In [20]:
selector = RFECV(lgbm, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
lgbm_col= np.where(selector.ranking_==1)
lgbm_col

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int64),)

In [21]:
selector = RFECV(grad, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
grad_col= np.where(selector.ranking_==1)
grad_col

(array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64),)

In [22]:
selector = RFECV(xg, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
xg_col= np.where(selector.ranking_==1)
xg_col

(array([ 0,  1,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64),)

In [13]:
selector = RFECV(lr, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
lr_col= np.where(selector.ranking_==1)
lr_col

(array([ 0,  2,  5,  6,  7,  9, 10, 11, 13, 14, 15, 16, 18, 24, 25, 27, 28,
        29], dtype=int64),)

In [16]:
selector = RFECV(svm, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
svm_col= np.where(selector.ranking_==1)
svm_col

(array([ 0,  2,  3,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21,
        22, 24, 25, 26, 27, 28, 29], dtype=int64),)

In [20]:
selector = RFECV(knn, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
knn_col= np.where(selector.ranking_==1)
knn_col

ValueError: when `importance_getter=='auto'`, the underlying estimator KNeighborsClassifier should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

In [19]:
selector = RFECV(nb, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
nb_col= np.where(selector.ranking_==1)
nb_col

ValueError: when `importance_getter=='auto'`, the underlying estimator GaussianNB should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.

# stacking with subsets of features

In [24]:
from mlxtend.feature_selection import ColumnSelector
from sklearn.pipeline import make_pipeline

In [25]:
pipe_rf = make_pipeline(ColumnSelector(cols=(0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)),rf)

In [26]:
pipe_ada = make_pipeline(ColumnSelector(cols=( 0,  1,  2,  3,  5,  6,  7,  8,  9, 13, 14, 15, 18, 24, 25, 26, 27,
       28)),ada)

In [27]:
pipe_extra = make_pipeline(ColumnSelector(cols=(0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29)),extra)

In [28]:
pipe_lgbm = make_pipeline(ColumnSelector(cols=(0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29)),lgbm)

In [29]:
pipe_grad = make_pipeline(ColumnSelector(cols=(0,  1,  2,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28)),grad)

In [30]:
pipe_xg = make_pipeline(ColumnSelector(cols=( 0,  1,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 21, 22, 23, 24, 25, 26, 27, 28)),xg)

In [31]:
pipe_nn = make_pipeline(ColumnSelector(cols=(0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)),nn)

In [32]:
stacking_result = []
stacking_names= []

sel_classifier= [pipe_rf, pipe_ada, pipe_extra, pipe_lgbm, pipe_grad, pipe_xg,pipe_nn]

nn = MLPClassifier(random_state=10,verbose = True)

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

params= {
    'meta_classifier__hidden_layer_sizes': [(12,12,12), (24,32,24), (6,6,6),(6,12,6),(12,6,6),(6,12,32,12,6)],
}

grid = GridSearchCV(estimator=scl, 
                    param_grid=params, 
                    cv=10,
                    refit=True,
                    n_jobs=-1,
                   verbose=3)

grid.fit(x_train, y_train)


Fitting 10 folds for each of 6 candidates, totalling 60 fits
Iteration 1, loss = 0.66338969
Iteration 2, loss = 0.53614736
Iteration 3, loss = 0.39954306
Iteration 4, loss = 0.25622798
Iteration 5, loss = 0.17034131
Iteration 6, loss = 0.13260528
Iteration 7, loss = 0.11604884
Iteration 8, loss = 0.10698643
Iteration 9, loss = 0.10111227
Iteration 10, loss = 0.09662548
Iteration 11, loss = 0.09187400
Iteration 12, loss = 0.08850970
Iteration 13, loss = 0.08741005
Iteration 14, loss = 0.08658204
Iteration 15, loss = 0.08620986
Iteration 16, loss = 0.08611321
Iteration 17, loss = 0.08587629
Iteration 18, loss = 0.08569520
Iteration 19, loss = 0.08574490
Iteration 20, loss = 0.08533916
Iteration 21, loss = 0.08555584
Iteration 22, loss = 0.08528068
Iteration 23, loss = 0.08519243
Iteration 24, loss = 0.08514844
Iteration 25, loss = 0.08517288
Iteration 26, loss = 0.08510580
Iteration 27, loss = 0.08501634
Iteration 28, loss = 0.08492141
Iteration 29, loss = 0.08483318
Iteration 30, loss =

GridSearchCV(cv=10,
             estimator=StackingCVClassifier(classifiers=[Pipeline(steps=[('columnselector',
                                                                          ColumnSelector(cols=(0,
                                                                                               1,
                                                                                               2,
                                                                                               3,
                                                                                               4,
                                                                                               5,
                                                                                               6,
                                                                                               7,
                                                                                               8,
      

In [33]:
df= pd.DataFrame(grid.cv_results_)
df.sort_values(by='rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
3     107.026419      6.908299         0.098081        0.012451   
5      99.697847      7.558476         0.083771        0.035604   
1      87.689222     14.729146         0.426258        0.491014   
4     109.405517      8.224351         0.163908        0.144353   
2     100.906956     12.485489         0.168474        0.158951   
0      80.692205     12.534129         0.678865        0.669525   

  param_meta_classifier__hidden_layer_sizes  \
3                                (6, 12, 6)   
5                        (6, 12, 32, 12, 6)   
1                              (24, 32, 24)   
4                                (12, 6, 6)   
2                                 (6, 6, 6)   
0                              (12, 12, 12)   

                                              params  split0_test_score  \
3  {'meta_classifier__hidden_layer_sizes': (6, 12...           0.983725   
5  {'meta_classifier__hidden_layer_sizes': (6, 12...           0.985533   
1  {'meta_classifier__hidden_layer_sizes': (24, 3...           0.984629   
4  {'meta_classifier__hidden_layer_sizes': (12, 6...           0.984629   
2  {'meta_classifier__hidden_layer_sizes': (6, 6,...           0.984629   
0  {'meta_classifier__hidden_layer_sizes': (12, 1...           0.983725   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
3           0.986438           0.974684           0.985533           0.985533   
5           0.983725           0.973779           0.984629           0.981013   
1           0.984629           0.974684           0.984629           0.983725   
4           0.984629           0.974684           0.984629           0.978300   
2           0.986438           0.972875           0.985533           0.980108   
0           0.985533           0.974684           0.983725           0.980108   

   split5_test_score  split6_test_score  split7_test_score  split8_test_score  \
3           0.974661           0.965611           0.955656           0.969231   
5           0.977376           0.969231           0.956561           0.967421   
1           0.974661           0.966516           0.955656           0.963801   
4           0.974661           0.965611           0.955656           0.966516   
2           0.975566           0.969231           0.954751           0.962896   
0           0.973756           0.963801           0.952941           0.965611   

   split9_test_score  mean_test_score  std_test_score  rank_test_score  
3           0.967421         0.974849        0.009909                1  
5           0.967421         0.974669        0.009001                2  
1           0.968326         0.974126        0.009813                3  
4           0.969231         0.973855        0.009186                4  
2           0.966516         0.973854        0.010070                5  
0           0.967421         0.973131        0.010068                6

# Feature Selection - SFS 

In [21]:
from sklearn.feature_selection import SequentialFeatureSelector as sfs

In [23]:
selector = sfs(knn, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
knn_col= np.where(selector.support_==1)
knn_col

(array([ 1,  2,  4,  5,  7,  8,  9, 11, 12, 13, 14, 17, 19, 22, 28],
       dtype=int64),)

In [24]:
selector = sfs(nb, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
nb_col= np.where(selector.support_==1)
nb_col

(array([ 1,  4,  6,  7,  8,  9, 10, 13, 14, 16, 18, 19, 21, 22, 28],
       dtype=int64),)

In [14]:
selector = sfs(rf, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
rf_col,= np.where(selector.support_==1)
rf_col

array([ 0,  1,  4,  5,  6,  7, 12, 13, 14, 19, 23, 24, 25, 27, 28],
      dtype=int64)

In [15]:
selector = sfs(ada, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
ada_col,= np.where(selector.support_==1)
ada_col

array([ 0,  2,  4,  5,  6,  7,  8, 12, 13, 14, 15, 18, 25, 28, 29],
      dtype=int64)

In [16]:
selector = sfs(extra, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
extra_col,= np.where(selector.support_==1)
extra_col

array([ 1,  2,  3,  5,  7,  8, 12, 13, 14, 16, 17, 18, 19, 27, 28],
      dtype=int64)

In [17]:
selector = sfs(lgbm, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
lgbm_col,= np.where(selector.support_==1)
lgbm_col

array([ 0,  1,  2,  4,  5,  7,  8, 11, 12, 13, 14, 17, 19, 27, 28],
      dtype=int64)

In [18]:
selector = sfs(grad, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
grad_col,= np.where(selector.support_==1)
grad_col

array([ 1,  2,  5,  7,  8,  9, 12, 13, 14, 15, 17, 19, 23, 27, 28],
      dtype=int64)

In [19]:
selector = sfs(xg, cv=5, n_jobs=-1)
selector = selector.fit(x, y)
xg_col,= np.where(selector.support_==1)
xg_col

array([ 0,  1,  4,  5,  7,  8, 11, 12, 13, 14, 16, 19, 24, 27, 28],
      dtype=int64)

# sfs - prediction

In [21]:
from mlxtend.feature_selection import ColumnSelector
from sklearn.pipeline import make_pipeline

In [22]:
pipe_rf = make_pipeline(ColumnSelector(cols=(0,  1,  4,  5,  6,  7, 12, 13, 14, 19, 23, 24, 25, 27, 28)),rf)

In [23]:
pipe_ada = make_pipeline(ColumnSelector(cols=( 0,  2,  4,  5,  6,  7,  8, 12, 13, 14, 15, 18, 25, 28, 29)),ada)

In [24]:
pipe_extra = make_pipeline(ColumnSelector(cols=(1,  2,  3,  5,  7,  8, 12, 13, 14, 16, 17, 18, 19, 27, 28)),extra)

In [25]:
pipe_lgbm = make_pipeline(ColumnSelector(cols=(0,  1,  2,  4,  5,  7,  8, 11, 12, 13, 14, 17, 19, 27, 28)),lgbm)

In [26]:
pipe_grad = make_pipeline(ColumnSelector(cols=(1,  2,  5,  7,  8,  9, 12, 13, 14, 15, 17, 19, 23, 27, 28)),grad)

In [27]:
pipe_xg = make_pipeline(ColumnSelector(cols=( 0,  1,  4,  5,  7,  8, 11, 12, 13, 14, 16, 19, 24, 27, 28)),xg)

In [28]:
pipe_nn = make_pipeline(ColumnSelector(cols=(0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)),nn)

In [29]:
stacking_result = []
stacking_names= []

sel_classifier= [pipe_rf, pipe_ada, pipe_extra, pipe_lgbm, pipe_grad, pipe_xg,pipe_nn]

nn = MLPClassifier(random_state=10,verbose = True)

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

params= {
    'meta_classifier__hidden_layer_sizes': [(6,12,32,12,6),(6,12,24,12,6)],
}

grid = GridSearchCV(estimator=scl, 
                    param_grid=params, 
                    cv=10,
                    refit=True,
                    n_jobs=-1,
                   )

grid.fit(x_train, y_train)


Iteration 1, loss = 0.57486861
Iteration 2, loss = 0.31610899
Iteration 3, loss = 0.13503531
Iteration 4, loss = 0.10429044
Iteration 5, loss = 0.09842933
Iteration 6, loss = 0.09413879
Iteration 7, loss = 0.09237259
Iteration 8, loss = 0.09120540
Iteration 9, loss = 0.09024314
Iteration 10, loss = 0.08993906
Iteration 11, loss = 0.08929203
Iteration 12, loss = 0.08831729
Iteration 13, loss = 0.08847302
Iteration 14, loss = 0.08782587
Iteration 15, loss = 0.08738810
Iteration 16, loss = 0.08727309
Iteration 17, loss = 0.08659673
Iteration 18, loss = 0.08660723
Iteration 19, loss = 0.08599151
Iteration 20, loss = 0.08688757
Iteration 21, loss = 0.08816975
Iteration 22, loss = 0.08647799
Iteration 23, loss = 0.08556798
Iteration 24, loss = 0.08570539
Iteration 25, loss = 0.08584986
Iteration 26, loss = 0.08479848
Iteration 27, loss = 0.08484325
Iteration 28, loss = 0.08460789
Iteration 29, loss = 0.08499865
Iteration 30, loss = 0.08530136
Iteration 31, loss = 0.08494998
Iteration 32, los

GridSearchCV(cv=10,
             estimator=StackingCVClassifier(classifiers=[Pipeline(steps=[('columnselector',
                                                                          ColumnSelector(cols=(0,
                                                                                               1,
                                                                                               4,
                                                                                               5,
                                                                                               6,
                                                                                               7,
                                                                                               12,
                                                                                               13,
                                                                                               14,
   

In [30]:
df= pd.DataFrame(grid.cv_results_)
df.sort_values(by='rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0      86.674466     11.567040         0.264206        0.237503   
1      65.674237     21.077635         0.367330        0.465083   

  param_meta_classifier__hidden_layer_sizes  \
0                        (6, 12, 32, 12, 6)   
1                        (6, 12, 24, 12, 6)   

                                              params  split0_test_score  \
0  {'meta_classifier__hidden_layer_sizes': (6, 12...           0.978300   
1  {'meta_classifier__hidden_layer_sizes': (6, 12...           0.979204   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.984629           0.971971           0.983725           0.980108   
1           0.983725           0.967450           0.983725           0.978300   

   split5_test_score  split6_test_score  split7_test_score  split8_test_score  \
0           0.969231           0.964706           0.959276           0.971041   
1           0.968326           0.963801           0.956561           0.971946   

   split9_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.967421         0.973041        0.007977                1  
1           0.968326         0.972136        0.008483                2