In [1]:
import pandas as pd
import numpy as np
import itertools

from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.metrics import *
from imblearn.metrics import *

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.ensemble import StackingClassifier
from mlxtend.classifier import StackingCVClassifier

from sklearn.neural_network import MLPClassifier


from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import matplotlib.pyplot as plt

In [2]:
data= pd.read_csv('mendeley_20.csv')
data

qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
0                3               0                  0              1   
1                5               0                  1              3   
2                2               0                  0              1   
3                4               0                  2              5   
4                2               0                  0              0   
...            ...             ...                ...            ...   
88642            3               1                  0              0   
88643            2               0                  0              0   
88644            2               1                  0              5   
88645            2               0                  0              1   
88646            2               0                  0              0   

       qty_questionmark_url  qty_equal_url  qty_at_url  qty_and_url  \
0                         0              0           0            0   
1                         0              3           0            2   
2                         0              0           0            0   
3                         0              0           0            0   
4                         0              0           0            0   
...                     ...            ...         ...          ...   
88642                     0              0           0            0   
88643                     0              0           0            0   
88644                     0              0           0            0   
88645                     0              0           0            0   
88646                     0              0           0            0   

       qty_exclamation_url  qty_space_url  ...  qty_ip_resolved  \
0                        0              0  ...                1   
1                        0              0  ...                1   
2                        0              0  ...                1   
3                        0              0  ...                1   
4                        0              0  ...                1   
...                    ...            ...  ...              ...   
88642                    0              0  ...                1   
88643                    0              0  ...                1   
88644                    0              0  ...                1   
88645                    0              0  ...                1   
88646                    0              0  ...                1   

       qty_nameservers  qty_mx_servers  ttl_hostname  tls_ssl_certificate  \
0                    2               0           892                    0   
1                    2               1          9540                    1   
2                    2               3           589                    1   
3                    2               0           292                    1   
4                    2               1          3597                    0   
...                ...             ...           ...                  ...   
88642                3               1          3597                    0   
88643                2               2           591                    0   
88644                2               5         14391                    1   
88645                1               1            52                    1   
88646                4               0           299                    0   

       qty_redirects  url_google_index  domain_google_index  url_shortened  \
0                  0                 0                    0              0   
1                  0                 0                    0              0   
2                  0                 0                    0              0   
3                  0                 0                    0              0   
4                  1                 0                    0              0   
...              ...               ...                  ...            ...   
88642        

In [3]:
x= data.drop(['phishing'],axis=1)
x

qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
0                3               0                  0              1   
1                5               0                  1              3   
2                2               0                  0              1   
3                4               0                  2              5   
4                2               0                  0              0   
...            ...             ...                ...            ...   
88642            3               1                  0              0   
88643            2               0                  0              0   
88644            2               1                  0              5   
88645            2               0                  0              1   
88646            2               0                  0              0   

       qty_questionmark_url  qty_equal_url  qty_at_url  qty_and_url  \
0                         0              0           0            0   
1                         0              3           0            2   
2                         0              0           0            0   
3                         0              0           0            0   
4                         0              0           0            0   
...                     ...            ...         ...          ...   
88642                     0              0           0            0   
88643                     0              0           0            0   
88644                     0              0           0            0   
88645                     0              0           0            0   
88646                     0              0           0            0   

       qty_exclamation_url  qty_space_url  ...  time_domain_expiration  \
0                        0              0  ...                      -1   
1                        0              0  ...                     150   
2                        0              0  ...                      -1   
3                        0              0  ...                      -1   
4                        0              0  ...                     306   
...                    ...            ...  ...                     ...   
88642                    0              0  ...                     334   
88643                    0              0  ...                     431   
88644                    0              0  ...                     712   
88645                    0              0  ...                      -1   
88646                    0              0  ...                      64   

       qty_ip_resolved  qty_nameservers  qty_mx_servers  ttl_hostname  \
0                    1                2               0           892   
1                    1                2               1          9540   
2                    1                2               3           589   
3                    1                2               0           292   
4                    1                2               1          3597   
...                ...              ...             ...           ...   
88642                1                3               1          3597   
88643                1                2               2           591   
88644                1                2               5         14391   
88645                1                1               1            52   
88646                1                4               0           299   

       tls_ssl_certificate  qty_redirects  url_google_index  \
0                        0              0                 0   
1                        1              0                 0   
2                        1              0                 0   
3                        1              0                 0   
4                        0              1                 0   
...                    ...            ...               ...   
88642                    0              0                 0   
88643              

In [4]:
y=data['phishing']
y

0        1
1        1
2        0
3        1
4        0
        ..
88642    0
88643    0
88644    1
88645    1
88646    0
Name: phishing, Length: 88647, dtype: int64

In [5]:
x_train=x
y_train=y

In [6]:
y.value_counts()

0    58000
1    30647
Name: phishing, dtype: int64

# defining models

In [7]:
knn= KNeighborsClassifier(n_neighbors=10,n_jobs=-1)
svm= SVC(random_state=10,kernel='rbf')
lr = LogisticRegression()

rf= RandomForestClassifier(n_jobs=-1,random_state=10)
ada= AdaBoostClassifier(random_state=100)
extra = ExtraTreesClassifier(n_jobs=-1,random_state=10)

lgbm = LGBMClassifier(n_jobs=-1,random_state=10)
grad = GradientBoostingClassifier()
xg = XGBClassifier(use_label_encoder =False, eval_metric='logloss')

nn= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (32,32,32), random_state=10)

In [8]:
classifiers= {
    "RandomForest": rf,
    "ExtraTree": extra,
    "gradBoost": grad,
    "adaboost": ada,
    "LGBM": lgbm,
    "xgb": xg,
    "nn":nn}

In [9]:
classifier_2 = nn

In [10]:
scores={'accuracy': make_scorer(accuracy_score),
        'recall' : make_scorer(recall_score),
        'precision':make_scorer(precision_score),
        'gmean': make_scorer(geometric_mean_score),
        'f1':make_scorer(f1_score),
        'roc': make_scorer(roc_auc_score)
        }

# base models

In [11]:
rf_result = cross_validate(rf, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(rf_result)
df.mean(axis=0)

fit_time          2.725133
score_time        0.041724
test_accuracy     0.971663
test_recall       0.961301
test_precision    0.956945
test_gmean        0.969185
test_f1           0.959111
test_roc          0.969220
dtype: float64

In [14]:
ada_result= cross_validate(ada, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(ada_result)
df.mean(axis=0)

fit_time          5.876793
score_time        0.101128
test_accuracy     0.936490
test_recall       0.907104
test_precision    0.909045
test_gmean        0.929284
test_f1           0.908056
test_roc          0.929561
dtype: float64

In [15]:
extra_result= cross_validate(extra, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(extra_result)
df.mean(axis=0)

fit_time          2.776407
score_time        0.045096
test_accuracy     0.970918
test_recall       0.959311
test_precision    0.956692
test_gmean        0.968139
test_f1           0.957996
test_roc          0.968181
dtype: float64

In [16]:
grad_result= cross_validate(grad, x_train, y_train, cv = 10, scoring=scores)
df= pd.DataFrame(grad_result)
df.mean(axis=0)

fit_time          22.501707
score_time         0.028397
test_accuracy      0.953478
test_recall        0.934610
test_precision     0.931095
test_gmean         0.948918
test_f1            0.932845
test_roc           0.949029
dtype: float64

In [17]:
lgbm_result= cross_validate(lgbm, x_train, y_train, cv = 10, scoring=scores, n_jobs=-1)
df= pd.DataFrame(lgbm_result)
df.mean(axis=0)

fit_time          3.501818
score_time        0.079918
test_accuracy     0.966812
test_recall       0.953274
test_precision    0.950870
test_gmean        0.963563
test_f1           0.952066
test_roc          0.963620
dtype: float64

In [19]:
xg_result= cross_validate(xg, x_train, y, cv = 10, scoring=scores, n_jobs=-1)
df= pd.DataFrame(xg_result)
df.mean(axis=0)

fit_time          28.009947
score_time         0.040733
test_accuracy      0.970828
test_recall        0.957777
test_precision     0.957863
test_gmean         0.967697
test_f1            0.957812
test_roc           0.967751
dtype: float64

In [21]:
nn_result= cross_validate(nn, x_train, y, cv = 10, scoring=scores,  n_jobs=-1)
df= pd.DataFrame(nn_result)
df.mean(axis=0)

fit_time          62.715342
score_time         0.037506
test_accuracy      0.921058
test_recall        0.897839
test_precision     0.878532
test_gmean         0.914952
test_f1            0.886950
test_roc           0.915583
dtype: float64

In [11]:
nb= GaussianNB()
nb_result= cross_validate(nb, x_train, y, cv = 10, scoring=scores)
df= pd.DataFrame(nb_result)
df.mean(axis=0)

fit_time          0.169213
score_time        0.023905
test_accuracy     0.842860
test_recall       0.628055
test_precision    0.883814
test_gmean        0.774996
test_f1           0.734265
test_roc          0.792209
dtype: float64

In [12]:
knn_result= cross_validate(knn, x_train, y, cv = 10, scoring=scores, n_jobs=-1)
df= pd.DataFrame(knn_result)
df.mean(axis=0)

fit_time           0.057712
score_time        16.391473
test_accuracy      0.866437
test_recall        0.763534
test_precision     0.835934
test_gmean         0.838485
test_f1            0.798083
test_roc           0.842172
dtype: float64

In [14]:
svm_result= cross_validate(svm, x_train, y, cv = 10, scoring=scores, n_jobs=-1)
df= pd.DataFrame(svm_result)
df.mean(axis=0)

fit_time          1845.801982
score_time          92.756810
test_accuracy        0.757984
test_recall          0.567266
test_precision       0.679751
test_gmean           0.697948
test_f1              0.618419
test_roc             0.713012
dtype: float64

In [13]:
lr_result= cross_validate(lr, x_train, y, cv = 10, scoring=scores,  n_jobs=-1)
df= pd.DataFrame(lr_result)
df.mean(axis=0)

fit_time          8.901156
score_time        0.021805
test_accuracy     0.893353
test_recall       0.797275
test_precision    0.883447
test_gmean        0.866992
test_f1           0.836984
test_roc          0.870698
dtype: float64

# stacking - proba

In [ ]:
# meta - nn,  cv - 10

stacking_result = []
stacking_names= []

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

sel_classifier= [rf, ada, extra, lgbm, grad, xg, nn]

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)


In [14]:
df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          21.672631
score_time         0.083033
test_accuracy      0.974759
test_recall        0.984243
test_precision     0.971064
test_gmean         0.973425
test_f1            0.977543
test_roc           0.973541
dtype: float64

In [31]:
sel_classifier= [rf, ada, extra, lgbm, grad, xg, nn]

nn_basic = MLPClassifier(random_state=10)

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_basic, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

params= {
    'meta_classifier__hidden_layer_sizes': [(12,12,12),(12,6,6),(6,12,32,12,6),(12,24,12,6)],
}

grid = GridSearchCV(estimator=scl, 
                    param_grid=params, 
                    cv=10,
                    refit=True,
                    n_jobs=-1)

grid.fit(x_train, y_train)


GridSearchCV(cv=10,
             estimator=StackingCVClassifier(classifiers=[RandomForestClassifier(n_jobs=-1,
                                                                                random_state=10),
                                                         AdaBoostClassifier(random_state=100),
                                                         ExtraTreesClassifier(n_jobs=-1,
                                                                              random_state=10),
                                                         LGBMClassifier(random_state=10),
                                                         GradientBoostingClassifier(),
                                                         XGBClassifier(base_score=None,
                                                                       booster=None,
                                                                       colsample_bylevel=None,
                                                                  

In [33]:
df= pd.DataFrame(grid.cv_results_)
df.sort_values(by='rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
1     897.227048     86.170097         1.450027        0.402412   
3     789.143794    172.485958         0.783166        0.869165   
0     960.579238    122.727922         1.266486        0.566797   
2    1030.604501     66.966603         1.008628        0.472403   

  param_meta_classifier__hidden_layer_sizes  \
1                                (12, 6, 6)   
3                           (12, 24, 12, 6)   
0                              (12, 12, 12)   
2                        (6, 12, 32, 12, 6)   

                                              params  split0_test_score  \
1  {'meta_classifier__hidden_layer_sizes': (12, 6...           0.976650   
3  {'meta_classifier__hidden_layer_sizes': (12, 2...           0.976537   
0  {'meta_classifier__hidden_layer_sizes': (12, 1...           0.976537   
2  {'meta_classifier__hidden_layer_sizes': (6, 12...           0.975973   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
1           0.974958           0.970446           0.975747           0.972363   
3           0.975296           0.970784           0.973604           0.972363   
0           0.975522           0.970446           0.975522           0.972702   
2           0.974732           0.971235           0.974281           0.972250   

   split5_test_score  split6_test_score  split7_test_score  split8_test_score  \
1           0.974055           0.973942           0.977550           0.976986   
3           0.973942           0.974281           0.977550           0.977098   
0           0.973378           0.974281           0.977550           0.976760   
2           0.973830           0.974168           0.977098           0.976873   

   split9_test_score  mean_test_score  std_test_score  rank_test_score  
1           0.975519         0.974822        0.002083                1  
3           0.975632         0.974709        0.002030                2  
0           0.974391         0.974709        0.002030                3  
2           0.974955         0.974540        0.001764                4

# feature selection

In [12]:
from sklearn.feature_selection import RFECV

In [13]:
selector = RFECV(rf, cv=3, n_jobs=-1)
selector = selector.fit(x, y)
rf_col,= np.where(selector.ranking_==1)
rf_col

array([  0,   1,   3,  18,  19,  20,  36,  37,  40,  41,  42,  43,  45,
        46,  48,  50,  51,  52,  56,  57,  58,  59,  60,  64,  65,  67,
        69,  70,  74,  75,  76,  83,  93,  95,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107], dtype=int64)

In [14]:
selector = RFECV(ada, cv=3, n_jobs=-1)
selector = selector.fit(x, y)
ada_col,= np.where(selector.ranking_==1)
ada_col

array([ 17,  18,  19,  20,  37,  41,  57,  60,  75,  93,  97,  98,  99,
       100, 102, 103, 105, 106, 110], dtype=int64)

In [15]:
selector = RFECV(extra, cv=3, n_jobs=-1)
selector = selector.fit(x, y)
extra_col= np.where(selector.ranking_==1)
extra_col

(array([  0,   1,   3,  18,  19,  36,  37,  43,  44,  54,  57,  61,  62,
         63,  72,  73,  75,  90,  97,  99, 100, 101, 102, 103, 104, 105,
        107], dtype=int64),)

In [13]:
selector = RFECV(lgbm, cv=3, n_jobs=-1)
selector = selector.fit(x, y)
lgbm_col= np.where(selector.ranking_==1)
lgbm_col

(array([  0,   1,   2,   3,   4,   5,   6,   7,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  30,  36,  37,  38,  39,  40,  41,
         42,  43,  45,  48,  51,  56,  57,  58,  59,  60,  62,  67,  68,
         69,  74,  75,  76,  77,  78,  81,  83,  92,  93,  94,  95,  96,
         97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
        110], dtype=int64),)

In [14]:
selector = RFECV(grad, cv=3, n_jobs=-1)
selector = selector.fit(x, y)
grad_col= np.where(selector.ranking_==1)
grad_col

(array([  3,  17,  18,  19,  20,  37,  41,  42,  46,  57,  60,  69,  74,
         75,  76,  97,  99, 100, 102, 103, 104, 105, 106, 107, 110],
       dtype=int64),)

In [15]:
selector = RFECV(xg, cv=3, n_jobs=-1)
selector = selector.fit(x, y)
xg_col= np.where(selector.ranking_==1)
xg_col

(array([  0,   1,   2,   3,   5,   6,  10,  12,  16,  17,  18,  19,  20,
         36,  37,  38,  40,  41,  42,  43,  45,  56,  57,  58,  59,  60,
         69,  74,  75,  76,  83,  93,  94,  95,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 110], dtype=int64),)

In [27]:
np.array(list(range(0,110)))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109])

# stacking with subsets of features

In [16]:
from mlxtend.feature_selection import ColumnSelector
from sklearn.pipeline import make_pipeline

In [17]:
pipe_rf = make_pipeline(ColumnSelector(cols=( 0,   1,   3,  18,  19,  20,  36,  37,  40,  41,  42,  43,  45,
        46,  48,  50,  51,  52,  56,  57,  58,  59,  60,  64,  65,  67,
        69,  70,  74,  75,  76,  83,  93,  95,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107)),rf)

In [18]:
pipe_ada = make_pipeline(ColumnSelector(cols=( 17,  18,  19,  20,  37,  41,  57,  60,  75,  93,  97,  98,  99,
       100, 102, 103, 105, 106, 110)),ada)

In [19]:
pipe_extra = make_pipeline(ColumnSelector(cols=(0,   1,   3,  18,  19,  36,  37,  43,  44,  54,  57,  61,  62,
         63,  72,  73,  75,  90,  97,  99, 100, 101, 102, 103, 104, 105,
        107)),extra)

In [20]:
pipe_lgbm = make_pipeline(ColumnSelector(cols=( 0,   1,   2,   3,   4,   5,   6,   7,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  30,  36,  37,  38,  39,  40,  41,
         42,  43,  45,  48,  51,  56,  57,  58,  59,  60,  62,  67,  68,
         69,  74,  75,  76,  77,  78,  81,  83,  92,  93,  94,  95,  96,
         97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
        110)),lgbm)

In [21]:
pipe_grad = make_pipeline(ColumnSelector(cols=(3,  17,  18,  19,  20,  37,  41,  42,  46,  57,  60,  69,  74,
         75,  76,  97,  99, 100, 102, 103, 104, 105, 106, 107, 110)),grad)

In [22]:
pipe_xg = make_pipeline(ColumnSelector(cols=( 0,   1,   2,   3,   5,   6,  10,  12,  16,  17,  18,  19,  20,
         36,  37,  38,  40,  41,  42,  43,  45,  56,  57,  58,  59,  60,
         69,  74,  75,  76,  83,  93,  94,  95,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 110)),xg)

In [28]:
pipe_nn = make_pipeline(ColumnSelector(cols=(0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109)),nn)

In [29]:
sel_classifier= [pipe_rf, pipe_ada, pipe_extra, pipe_lgbm, pipe_grad, pipe_xg, pipe_nn]

nn_meta= MLPClassifier(activation = "relu", alpha = 0.001, hidden_layer_sizes = (6,12,24,12,6), random_state=10)

scl = StackingCVClassifier(classifiers= sel_classifier,
                            meta_classifier = nn_meta, # use meta-classifier
                            use_probas = True,   # use_probas = True/False
                            random_state = 10)

st_result= cross_validate(scl, x_train, y, cv = 10, scoring=scores,n_jobs=-1)

In [30]:
df= pd.DataFrame(st_result)
df.mean(axis=0)

fit_time          400.310504
score_time          0.431497
test_accuracy       0.974438
test_recall         0.965347
test_precision      0.960940
test_gmean          0.972262
test_f1             0.963116
test_roc            0.972294
dtype: float64